env:
    global:
        # Your package name
        - PACKAGE="EasyClangComplete"
        - SUBLIME_TEXT_VERSION="3"

language:
    - python

matrix:
    include:
    - os: linux
      env: DISTRO="Ubuntu 14.04"
      dist: trusty
      sudo: required
      addons:
          apt:
            packages:
            - clang-3.4
    - os: linux
      env: DISTRO="Ubuntu 16.04"
      dist: xenial
      sudo: required
      addons:
          apt:
            packages:
            - clang-3.8
    - os: osx
      env: DISTRO="OSX"

before_install:
    - curl -OL https://raw.githubusercontent.com/randy3k/UnitTesting/master/sbin/travis.sh
    # enable gui, see https://docs.travis-ci.com/user/gui-and-headless-browsers
    - if [ "$TRAVIS_OS_NAME" == "linux"  ]; then
            export DISPLAY=:99.0;
            sh -e /etc/init.d/xvfb start;
            sudo pip install --upgrade pep8 pep257;
            sudo pip install coverage codacy-coverage;
      fi
    - ls /usr/bin | grep clang
    - if [ "$DISTRO" == "Ubuntu 14.04" ]; then
            sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.4 100;
            sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.4 100;
      fi
    - if [ "$DISTRO" == "Ubuntu 16.04" ]; then
            sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.8 100;
            sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.8 100;
      fi

install:
    - sh travis.sh bootstrap

script:
    - ls
    - sh travis.sh run_tests --coverage
    - if [ "$TRAVIS_OS_NAME" == "linux"  ]; then
            coverage xml -o coverage.xml;
      fi

after_success:
    - python-codacy-coverage -r coverage.xml

notifications:
    email: false
