env:
    global:
        # Your package name
        - PACKAGE="EasyClangComplete"
        - SUBLIME_TEXT_VERSION="3"
matrix:
    include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: xenial
      sudo: required
    - os: osx

before_install:
    - curl -OL https://raw.githubusercontent.com/randy3k/UnitTesting/master/sbin/travis.sh
    # enable gui, see https://docs.travis-ci.com/user/gui-and-headless-browsers
    - if [ "$TRAVIS_OS_NAME" == "linux"  ]; then
            export DISPLAY=:99.0;
            sh -e /etc/init.d/xvfb start;
            sudo apt-get update -qq -y;
            sudo apt-get install -yqq clang-3.4;
            sudo pip install --upgrade pep8 pep257;
            sudo pip install coverage codacy-coverage;
      fi

install:
    - sh travis.sh bootstrap

script:
    - ls
    - sh travis.sh run_tests --coverage
    - if [ "$TRAVIS_OS_NAME" == "linux"  ]; then
            coverage xml -o coverage.xml;
      fi
    # testing syntax_test files
    # - sh travis.sh run_syntax_tests

after_success:
    - python-codacy-coverage -r coverage.xml

notifications:
    email: false
